import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PageBody from "./PageBody";
import { SidebarContextProvider } from "./context/SidebarContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Webフロントエンド入門",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // <Html> (Next.js Custom Component)
  //  - The <Html> component (capitalized H) is specific to Next.js.
  //  - It's used in custom Document files (usually in pages/_document.js or pages/_document.tsx)
  //    to customize the HTML document structure.
  //  - It provides a way to override the default HTML template that Next.js uses to render your page.
  // When you need to customize the <html>, <head>, or <body> tags, you use the <Html>, <Head>,
  // and <Main> components provided by Next.js inside the _document.js (or _document.tsx) file.
  // These components enable you to adjust things like language attributes, meta tags, or global styles.
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarContextProvider>
          <PageBody>{children}</PageBody>
        </SidebarContextProvider>
      </body>
    </html>
  );
}
