import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const contents = [
  {
    title: "Home",
    path: "/",
  },
  {
    title: "JavaScript",
    path: "/javascript",
  },
  {
    title: "React",
    path: "/react",
  },
];

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // <Html> (Next.js Custom Component)
  //  - The <Html> component (capitalized H) is specific to Next.js.
  //  - It's used in custom Document files (usually in pages/_document.js or pages/_document.tsx)
  //    to customize the HTML document structure.
  //  - It provides a way to override the default HTML template that Next.js uses to render your page.
  // When you need to customize the <html>, <head>, or <body> tags, you use the <Html>, <Head>,
  // and <Main> components provided by Next.js inside the _document.js (or _document.tsx) file.
  // These components enable you to adjust things like language attributes, meta tags, or global styles.
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="sticky top-0 z-10 bg-white flex items-center justify-between w-full h-16 px-4 border-b">
          {/* Page Title */}
          <div className="flex-shrink-0 text-white text-xl font-semibold bg-blue-500 px-4 py-1">
            Webフロントエンド入門
          </div>

          {/* Navigation Links */}
          <div className="hidden sm:block sm:ml-6">
            <div className="flex space-x-4">
              {contents.map((content, index) => (
                <Link
                  key={index}
                  href={`${content.path}`}
                  className="block text-gray-600 px-3 py-2 rounded-md text-sm font-medium hover:bg-gray-300"
                >
                  {content.title}
                </Link>
              ))}
            </div>
          </div>

          {/* Mobile Menu (Hidden by default) */}
          <div className="sm:hidden" id="mobile-menu">
            <div className="px-2 pt-2 pb-3 space-y-1">
              {contents.map((content, index) => (
                <Link
                  key={index}
                  href={content.path}
                  className="text-white block px-3 py-2 rounded-md text-base font-medium hover:bg-blue-700"
                >
                  {content.title}
                </Link>
              ))}
            </div>
          </div>
        </nav>
        {/* Main Content (Right Section) */}
        <div className="flex">{children}</div>
        {/* Footer with Copyright */}
        <footer className="bg-gray-800 text-white py-4 text-center">
          <p>
            &copy; {new Date().getFullYear()} Daisuke Takahashi. All Rights
            Reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
